#!/usr/bin/env -S macaws deploy
Resources:

  BirdFoodInfrastructureCreatorUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: birdfood-infrastructure-creator
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  BirdFoodInfrastructureCreatorAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 1
      Status: Active
      UserName: !Ref BirdFoodInfrastructureCreatorUser
  BirdFoodInfrastructureCreatorSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: birdfood-infrastructure-creator-credentials
      Description: AWS User credentials for the birdfood-infrastructure-creator user
      SecretString: !Sub '{ "AccessKeyId": "${BirdFoodInfrastructureCreatorAccessKey}", "SecretAccessKey": "${BirdFoodInfrastructureCreatorAccessKey.SecretAccessKey}" }'
      Tags:
        - Key: UserCredentialsFor
          Value: birdfood-infrastructure-creator
        - Key: UserCredentialType
          Value: CLI

  BirdFoodAlexAndJamieAccountUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: birdfood-alex-and-jamie-account
      Policies:
        - PolicyName: AccessDynamoDbEntriesForThisHousehold
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:Query"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:BatchWriteItem"
                Resource:
                  - "arn:*:dynamodb:*:*:table/BirdFoodItems"
                Condition:
                  ForAllValues:StringEquals: {
                    "dynamodb:LeadingKeys": [ "bird-family-household" ]
                  }
  BirdFoodAlexAndJamieAccountAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 1
      Status: Active
      UserName: !Ref BirdFoodAlexAndJamieAccountUser
  BirdFoodAlexAndJamieAccountSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: birdfood-alex-and-jamie-account-credentials
      Description: AWS User credentials for the birdfood-alex-and-jamie-account user
      SecretString: !Sub '{ "AccessKeyId": "${BirdFoodAlexAndJamieAccountAccessKey}", "SecretAccessKey": "${BirdFoodAlexAndJamieAccountAccessKey.SecretAccessKey}" }'
      Tags:
        - Key: UserCredentialsFor
          Value: birdfood-alex-and-jamie-account
        - Key: UserCredentialType
          Value: CLI
